### ISSUE TITLE
How to filter out error log output to specified file？

### ISSUE THREAD

**Issue by Jim-Rae** [yidinghan/koa2-winston#10]
I want to filter out error log output to 'error.log'. 
Like 'express-winston',
`app.use(expressWinston.errorLogger({
    transports: [
        new winston.transports.Console({
          json: true,
          colorize: true
        }),
        new winston.transports.File({
          filename: 'logs/error.log'
        })
    ]
}));`
So how to achieve the same function in 'koa2-winston'?

**Comment by yidinghan** [comment]
You can pass a logger created with multiple transports.

https://github.com/yidinghan/koa2-winston/blob/7b8cd178d6214208b169d2f0b4fe65831b906cb8/scripts/issue-10.js#L14

**Comment by yidinghan** [comment]
```shell
➜  koa2-winston git:(issue-10) ✗ cat tmp.error.log
cat: tmp.error.log: No such file or directory
➜  koa2-winston git:(issue-10) ✗ node scripts/issue-10.js
{"req":{"method":"get","url":"/ding","header":{"cookie":"ding"}},"started_at":1563761207987,"message":"HTTP get /ding","res":{"_events":{},"_eventsCount":0},"duration":1,"level":"info"}
➜  koa2-winston git:(issue-10) ✗ cat tmp.error.log
{"req":{"method":"get","url":"/ding","header":{"cookie":"ding"}},"started_at":1563761207987,"message":"HTTP get /ding","res":{"_events":{},"_eventsCount":0},"duration":1,"level":"info"}
```

**Comment by yidinghan** [comment]
Also, params `transports` support `type: Array`

https://github.com/yidinghan/koa2-winston/blob/117a336f342d8e9ffe06fe81e41d62586ebae8fd/scripts/issue-10-2.js#L9

```shell
➜  koa2-winston git:(issue-10) rm tmp.error.log
➜  koa2-winston git:(issue-10) node scripts/issue-10-2.js
{"started_at":1563774150719,"duration":2,"level":"info","message":"HTTP get /ding","req":{"header":{"cookie":null},"url":"/ding","method":"get"},"res":{}}
➜  koa2-winston git:(issue-10) cat tmp.error.log
{"started_at":1563774150719,"duration":2,"level":"info","message":"HTTP get /ding","req":{"header":{"cookie":null},"url":"/ding","method":"get"},"res":{}}
```
