### ISSUE TITLE
Update peerDependencies: winston to 3.0

### ISSUE THREAD

**Issue by hebinhuang** [yidinghan/koa2-winston#4]
The latest version of Winston is currently 3.0+. It should update it in peerDependencies.

**Comment by yidinghan** [comment]
Winston v3 has a lot of API [Breaking changes](https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md#removed-winstontransportsfileconsolehttp-formatting-options), but I would love to upgrade.

Thanks for reminding.

**Comment by mcmunder** [comment]
I created https://github.com/yidinghan/koa2-winston/pull/5 with updated dependencies. Thanks for writing koa2-winston ;-)

**Comment by yidinghan** [comment]
@mcmunder What a great job.

**Comment by yidinghan** [comment]
koa2-winston@3 was just launched a few minutes ago and is ready for upgrade.
